# ---------------------------------------------------- #
#                                                      #
#  This configuration helps you to customize XWorld    #
#                                                      #
# ---------------------------------------------------- #

# true - Console and/or Log-File shows debug-messages
# false - No debug-messages were shown
debug: false

# true - Console and/or Log-File displays permission errors
# false - No pernussoin errors were shown
displaypermerror: true
